{
 "title": "Demo Status",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Granularity", "query": "5" }
  ]
 },
 "panels": [
  {
   "title": "LiveAssist Chat Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,count(*) AS NumChatMessages FROM \"liveassist_chat\".\"chat_messages\" WHERE  ( timestamp >= $__fromTime AND timestamp <= $__toTime ) GROUP BY timestamp ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "LiveAssist Message Response Time (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\n  SELECT\n    tenant_id,\n    chain_id,\n    `timestamp`,\n    role\n  FROM \"liveassist_chat\".\"chat_messages\"\n  WHERE\n    $__timeFilter(`timestamp`)\n    AND role IN ('user', 'assistant')         -- only roles we care about\n),\nsorted AS (\n  SELECT\n    chain_id,\n    -- Array of tuples (ts, role) sorted by timestamp\n    arraySort(groupArray(tuple(`timestamp`, role))) AS evts\n  FROM filtered\n  GROUP BY chain_id\n)\nSELECT\n  pair.2.1 AS time,                                   -- assistant msg timestamp\n  dateDiff('second', pair.1.1, pair.2.1) AS value,    -- response time in seconds\n  chain_id AS metric\nFROM\n(\n  SELECT\n    chain_id,\n    arrayJoin(\n      arrayZip(\n        arrayPopBack(evts),    -- previous (ts, role)\n        arrayPopFront(evts)    -- current  (ts, role)\n      )\n    ) AS pair\n  FROM sorted\n)\nWHERE pair.1.2 = 'user' AND pair.2.2 = 'assistant'    -- user → assistant only\nORDER BY time\nLIMIT 1000;\n\n\n\n"
    }
   ]
  },
  {
   "title": "LA Used Tables (27)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    row_number() OVER () AS row_num,\n    name AS table_name\nFROM system.tables\nWHERE database = 'liveassist'\nORDER BY name;\n"
    }
   ]
  },
  {
   "title": "Basic Traffic by Device (Bytes)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    d.name AS Dscp,\n    SUM(SumOctets)/5 AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets)/5 AS TotalPackets,\n    SUM(SumOctets)*8/5/60 AS AverageBitRate,\n    AVG(SumPackets)/5/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/5/60 AS PeakBitRate,\n    MAX(SumPackets)/5/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_5m_dist as f\nJOIN livenx_flowdb.dscp AS d ON toUInt8(f.Dscp) = d.dscp\nWHERE\n    time >= 1708095989 AND time <= 1708096889 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND  \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName, Dscp\nLIMIT 1000",
     "rawSql": "SELECT\n    DeviceSerial,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    SUM(SumFlowCount) AS FlowCount\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) \nGROUP BY DeviceSerial",
     "round": "0s"
    }
   ]
  },
  {
   "title": "AVC Traffic by Device (Bytes)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    d.name AS Dscp,\n    SUM(SumOctets)/5 AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets)/5 AS TotalPackets,\n    SUM(SumOctets)*8/5/60 AS AverageBitRate,\n    AVG(SumPackets)/5/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/5/60 AS PeakBitRate,\n    MAX(SumPackets)/5/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_5m_dist as f\nJOIN livenx_flowdb.dscp AS d ON toUInt8(f.Dscp) = d.dscp\nWHERE\n    time >= 1708095989 AND time <= 1708096889 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND  \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName, Dscp\nLIMIT 1000",
     "rawSql": "SELECT\n    DeviceSerial,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    SUM(SumFlowCount) AS FlowCount\nFROM livenx_flowdb.avc_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) \nGROUP BY DeviceSerial",
     "round": "0s"
    }
   ]
  },
  {
   "title": "MediaNet Traffic by Device (Bytes)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    d.name AS Dscp,\n    SUM(SumOctets)/5 AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets)/5 AS TotalPackets,\n    SUM(SumOctets)*8/5/60 AS AverageBitRate,\n    AVG(SumPackets)/5/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/5/60 AS PeakBitRate,\n    MAX(SumPackets)/5/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_5m_dist as f\nJOIN livenx_flowdb.dscp AS d ON toUInt8(f.Dscp) = d.dscp\nWHERE\n    time >= 1708095989 AND time <= 1708096889 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND  \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName, Dscp\nLIMIT 1000",
     "rawSql": "SELECT\n    DeviceSerial,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    SUM(SumFlowCount) AS FlowCount\nFROM livenx_flowdb.medianet_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time)\nGROUP BY DeviceSerial",
     "round": "0s"
    }
   ]
  },
  {
   "title": "SNMP Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "/* SNMP inBytes counter → BYTES/SEC (no window funcs, sorted by time ASC) */\nWITH base AS (\n  SELECT\n    DeviceId,\n    Tags['description'] AS Memory,\n    time,\n    ifNull(AVG(MetricValue), 0.) AS v                 -- ensure non-null\n  FROM livenx_snmpdb.device_metric_dist\n  WHERE MetricName LIKE '%emory%'\n    AND $__timeFilter(time)\n  GROUP BY\n    DeviceId, Memory, time\n),\nagg AS (\n  SELECT\n    DeviceId,\n    Memory,\n    /* sort (time,value) tuples by time */\n    arraySort(x -> x.1, groupArray( (time, v) )) AS tv,\n    arrayMap(x -> x.1, tv) AS times,\n    arrayMap(x -> ifNull(x.2, 0.), tv) AS vals,          -- Array(Float64)\n    arrayDifference(vals) AS diffs,                      -- first element = 0\n    /* seconds between samples (same length as times/vals) */\n    arrayDifference(arrayMap(x -> toUnixTimestamp(x.1), tv)) AS dt\n  FROM base\n  GROUP BY\n    DeviceId, Memory\n),\nflat AS (\n  SELECT\n    DeviceId,\n    Memory,\n    /* drop the synthetic first delta with arraySlice(..., 2) */\n    arraySlice(times, 2) AS t_arr,\n    arraySlice(diffs, 2) AS d_arr,\n    arraySlice(dt, 2)    AS s_arr\n  FROM agg\n)\nSELECT\n  t AS time,\n  DeviceId,\n  Memory,\n  /* clip negatives from resets; for wrap handling use IF(d < 0, d + 4294967296, d) for 32-bit, or + 18446744073709551616 for 64-bit */\n  if(secs > 0, greatest(d, 0) / secs, 0) AS Mem\nFROM flat\nARRAY JOIN\n  t_arr AS t,\n  d_arr AS d,\n  s_arr AS secs\n/* Strict global sort so the consumer sees ascending time */\nORDER BY time ASC, DeviceId, Memory;\n"
    }
   ]
  },
  {
   "title": "SNMP CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "/* SNMP inBytes counter → BYTES/SEC (no window funcs, sorted by time ASC) */\nWITH base AS (\n  SELECT\n    DeviceId,\n    Tags['description'] AS CPU,\n    time,\n    ifNull(AVG(MetricValue), 0.) AS v                 -- ensure non-null\n  FROM livenx_snmpdb.device_metric_dist\n  WHERE MetricName LIKE '%cpu%'\n    AND $__timeFilter(time)\n  GROUP BY\n    DeviceId, CPU, time\n),\nagg AS (\n  SELECT\n    DeviceId,\n    CPU,\n    /* sort (time,value) tuples by time */\n    arraySort(x -> x.1, groupArray( (time, v) )) AS tv,\n    arrayMap(x -> x.1, tv) AS times,\n    arrayMap(x -> ifNull(x.2, 0.), tv) AS vals,          -- Array(Float64)\n    arrayDifference(vals) AS diffs,                      -- first element = 0\n    /* seconds between samples (same length as times/vals) */\n    arrayDifference(arrayMap(x -> toUnixTimestamp(x.1), tv)) AS dt\n  FROM base\n  GROUP BY\n    DeviceId, CPU\n),\nflat AS (\n  SELECT\n    DeviceId,\n    CPU,\n    /* drop the synthetic first delta with arraySlice(..., 2) */\n    arraySlice(times, 2) AS t_arr,\n    arraySlice(diffs, 2) AS d_arr,\n    arraySlice(dt, 2)    AS s_arr\n  FROM agg\n)\nSELECT\n  t AS time,\n  DeviceId,\n  CPU,\n  /* clip negatives from resets; for wrap handling use IF(d < 0, d + 4294967296, d) for 32-bit, or + 18446744073709551616 for 64-bit */\n  if(secs > 0, greatest(d, 0) / secs, 0) AS CPUs\nFROM flat\nARRAY JOIN\n  t_arr AS t,\n  d_arr AS d,\n  s_arr AS secs\n/* Strict global sort so the consumer sees ascending time */\nORDER BY time ASC, DeviceId, CPU;\n"
    }
   ]
  },
  {
   "title": "Available SNMP Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    DeviceId,\n    MetricName\nFROM livenx_snmpdb.device_metric_dist\nWHERE time >= $__fromTime\n  AND time <= $__toTime;\n"
    }
   ]
  },
  {
   "title": "OTEL Collector Clickhouse Sent/Failed Metric Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_metric_points[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(otelcol_exporter_send_failed_metric_points[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OTEL Collector Clickhouse Sent/Failed Log Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_log_records[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(otelcol_exporter_send_failed_log_records[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OTEL Collector Clickhouse Sent/Failed Spans Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_spans[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(otelcol_exporter_send_failed_spans[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNMP Traps (per 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT  \n    toStartOfMinute(toDateTime(Timestamp)) AS bucket,\n    count() AS count\nFROM liveassist.SNMP_Traps_OpenTelemetry_Log_Data\nWHERE $__timeFilter(Timestamp) \nGROUP BY bucket\nORDER BY bucket ASC\n "
    }
   ]
  },
  {
   "title": "LiveFlow DDI/Security Findings From LiveWire (per 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT  \n    toStartOfMinute(toDateTime(time)) AS bucket,\n    count() AS count\nFROM livenx_platformdb.si_findings_dist\nWHERE $__timeFilter(time) \nGROUP BY bucket\nORDER BY bucket ASC\n "
    }
   ]
  },
  {
   "title": "Syslog Logs Received (per 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT  \n    toStartOfMinute(toDateTime(Timestamp)) AS bucket,\n    count() AS count\nFROM liveassist.SYSLOG_OpenTelemtry_Log_Data\nWHERE $__timeFilter(Timestamp) \nGROUP BY bucket\nORDER BY bucket ASC\n "
    }
   ]
  },
  {
   "title": "Running Configs",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"liveassist\".\"Router_Config_OpenTelemetry_Log_Data\" LIMIT 1000"
    }
   ]
  },
  {
   "title": "Golden Configs",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"liveassist\".\"Recommended_Router_Config_For_LiveNX_OpenTelemetry_Log_Data\" LIMIT 1000"
    }
   ]
  },
  {
   "title": "iPerf Tests (Every six hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(Timestamp) as time,\n  count() as ` `,\n  ServiceName\nFROM otel_traces\nWHERE\n   $__timeFilter(Timestamp)\n  AND ServiceName IN ('iperf')\nGROUP BY ServiceName, time\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "title": "ThousandEyes Tests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(Timestamp) as time,\n  count() as ` `,\n  ServiceName\nFROM otel_traces\nWHERE\n   $__timeFilter(Timestamp)\n  AND ServiceName IN ('thousandeyes')\nGROUP BY ServiceName, time\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "title": "IPAM Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"liveassist\".\"BlueCat_IPAM_IP_Management_Address_Devices\" LIMIT 1000"
    }
   ]
  },
  {
   "title": "Portnox Log Data (per 1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT  \n    toStartOfMinute(toDateTime(Timestamp)) AS bucket,\n    count() AS count\nFROM liveassist.Portnox_OpenTelemetry_Log_Data\nWHERE $__timeFilter(Timestamp) \nGROUP BY bucket\nORDER BY bucket ASC\n "
    }
   ]
  },
  {
   "title": "K8s Metrics (tcp.bytes per Source/Dest containers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TimeUnix, Attributes['source.container.name'] AS SourceContainer,Attributes['dest.container.name'] AS DestContainer, SUM(Value) FROM otel_metrics_sum \nWHERE $__timeFilter(TimeUnix) AND Attributes['sf_product'] = 'network-explorer' AND MetricName = 'tcp.bytes' AND Attributes['source.container.name'] != '' AND Attributes['dest.container.name'] !=''\nGROUP BY TimeUnix, Attributes['source.container.name'],Attributes['dest.container.name'] ORDER BY TimeUnix ASC"
    }
   ]
  },
  {
   "title": "eBPF Metrics (# data points per 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfMinute(toDateTime(TimeUnix)) AS bucket,\n  count() AS value\nFROM otel_metrics_sum\nWHERE $__timeFilter(toDateTime(TimeUnix))\nGROUP BY bucket\nORDER BY bucket\n"
    }
   ]
  },
  {
   "title": "uptime(oldest)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (avg by (groupname) (namedprocess_namegroup_oldest_start_time_seconds{instance=~\"localhost\"} > 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dynamic Dashboard Views",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT\n    row_number() OVER () AS row_num,\n    name AS table_name\nFROM system.tables\nWHERE database = 'network_observability'\nORDER BY name;\n"
    }
   ]
  },
  {
   "title": "ARP Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"liveassist\".\"ARP_Information\" LIMIT 1000"
    }
   ]
  }
 ]
}