{
 "title": "LiveNX Performance",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Flows Received (flows/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Flows/sec" } },
   "targets": [
    {
     "expr": "rate(livenx_flow_record_received_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flows Packets Dropped (packets/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(livenx_flow_packet_dropped_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throttling Duration (secs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(livenx_throttling_duration_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollups Failed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_failed_total[$__rate_interval])) by (table,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extraction Max Threads (#)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "livenx_extraction_max_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Extraction Active Threads (#)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livenx_extraction_active_threads",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Queue Capacity (#)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "livenx_pipeline_queue_capacity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pipeline Queue Size (#)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "livenx_pipeline_queue_size", "legendFormat": "{{pipeline}}:{{queue}}" }
   ]
  },
  {
   "title": "Rollup Elapsed Times Basic Flow 1m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_seconds_sum{tableFamily=\"Basic\",bin=\"1m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_seconds_count{tableFamily=\"Basic\",bin=\"1m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LiveNX FlowDB Query performance over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(query_start_time) as time,\n       normalizeQuery(query) AS normalized_query,\n       query_duration_ms\nFROM system.query_log\nWHERE normalized_query NOT ILIKE 'INSERT INTO%' AND normalized_query LIKE '%livenx_flowdb%' AND type != 'QueryStart' AND $__timeFilter(event_time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Query performance by type over time (1m only)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(query_start_time) as time,\n       normalizeQuery(query) AS normalized_query,\n       query_duration_ms\nFROM system.query_log\nWHERE type != 'QueryStart' AND query LIKE '%SELECT toStartOfMinute%'\n  AND $__timeFilter(event_time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Rollup Elapsed Times 1m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_seconds_sum{bin=\"1m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_seconds_count{bin=\"1m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Elapsed Times Basic Flow 5m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_seconds_sum{bin=\"5m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_seconds_count{bin=\"5m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Elapsed Times Basic Flow 60m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_seconds_sum{bin=\"60m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_seconds_count{bin=\"60m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Elapsed Times Basic Flow 360m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_seconds_sum{bin=\"360m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_seconds_count{bin=\"360m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Wait Times Basic Flow 1m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_wait_time_per_table_seconds_sum{table=~\".*_${Granularity}m\"}[$__rate_interval])/delta(livenx_rollup_wait_time_per_table_seconds_sum{table=~\".*_${Granularity}m\"}[$__rate_interval])) by (table,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Wait Times Basic Flow 5m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_wait_time_per_table_seconds_sum{table=~\".*_5m\"}[$__rate_interval])/delta(livenx_rollup_wait_time_per_table_seconds_sum{table=~\".*_5m\"}[$__rate_interval])) by (table,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Wait Times Basic Flow 60m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_wait_time_per_table_seconds_sum{table=~\".*_60m\"}[$__rate_interval])/delta(livenx_rollup_wait_time_per_table_seconds_sum{table=~\".*_60m\"}[$__rate_interval])) by (table,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Wait Times Basic Flow 360m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_wait_time_per_table_seconds_sum{table=~\".*_360m\"}[$__rate_interval])/delta(livenx_rollup_wait_time_per_table_seconds_sum{table=~\".*_360m\"}[$__rate_interval])) by (table,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Delayed Times 1m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_delayed_time_seconds_sum{bin=\"1m\"}[$__rate_interval])/delta(livenx_rollup_delayed_time_seconds_count{bin=\"1m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Delayed Times 5m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_delayed_time_seconds_sum{bin=\"5m\"}[$__rate_interval])/delta(livenx_rollup_delayed_time_seconds_count{bin=\"5m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Delayed Times 60m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_delayed_time_seconds_sum{bin=\"60m\"}[$__rate_interval])/delta(livenx_rollup_delayed_time_seconds_count{bin=\"60m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Delayed Times Basic Flow 360m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_delayed_time_seconds_sum{bin=\"360m\"}[$__rate_interval])/delta(livenx_rollup_delayed_time_seconds_count{bin=\"360m\"}[$__rate_interval])) by (tableFamily,tableName,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insertion Record Count (#/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(livenx_insertion_record_count_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insertion Extract Encode Time (secs)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_insertion_extract_encode_time_seconds_sum[$__rate_interval])/delta(livenx_insertion_extract_encode_time_seconds_count[$__rate_interval])) by (table,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insertion Time (secs)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_insertion_time_seconds_sum[$__rate_interval])/delta(livenx_insertion_time_seconds_count[$__rate_interval])) by (table,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insertion Interval Time (secs)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_insertion_interval_seconds_sum[$__rate_interval])/delta(livenx_insertion_interval_seconds_count[$__rate_interval])) by (table,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insertion Delay Time (secs)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_insertion_time_delay_seconds_sum[$__rate_interval])/delta(livenx_insertion_time_delay_seconds_count[$__rate_interval])) by (table,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insertion Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_insertion_size_bytes_sum[$__rate_interval])/delta(livenx_insertion_size_bytes_count[$__rate_interval])) by (table,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Elapsed Times Basic Flow Tables 1m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_per_table_seconds_sum{table=~\".*_1m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_per_table_seconds_count{table=~\".*_1m\"}[$__rate_interval])) by (table,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Elapsed Times Basic Flow Tables 5m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_per_table_seconds_sum{table=~\".*_5m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_per_table_seconds_count{table=~\".*_5m\"}[$__rate_interval])) by (table,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Elapsed Times Basic Flow Tables 60m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_per_table_seconds_sum{table=~\".*_60m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_per_table_seconds_count{table=~\".*_60m\"}[$__rate_interval])) by (table,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollup Elapsed Times Basic Flow Tables 360m (secs)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(livenx_rollup_elapsed_time_per_table_seconds_sum{table=~\".*_360m\"}[$__rate_interval])/delta(livenx_rollup_elapsed_time_per_table_seconds_count{table=~\".*_360m\"}[$__rate_interval])) by (table,granularity,instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}