{
 "title": "Synthetics Path Visualization",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AgentName",
    "query": "SELECT SpanAttributes['agent.name'] FROM otel_traces WHERE $__timeFilter(Timestamp) "
   },
   {
    "name": "TestName",
    "query": "SELECT SpanAttributes['test.name'] FROM otel_traces WHERE $__timeFilter(Timestamp)  AND ( SpanAttributes['agent.name'] = '${AgentName}' )"
   },
   {
    "name": "TraceID",
    "query": "SELECT DISTINCT TraceId FROM otel_traces WHERE ParentSpanId = ''  AND SpanAttributes['test.name'] = '${TestName}'\nAND ( SpanAttributes['agent.name'] = '${AgentName}' )\n AND $__timeFilter(Timestamp) "
   },
   {
    "name": "PathID",
    "query": "SELECT DISTINCT SpanAttributes['path.id'] FROM otel_traces WHERE ParentSpanId = ''  AND SpanAttributes['test.name'] = '${TestName}'\nAND ( SpanAttributes['agent.name'] = '${AgentName}' )\nAND ( TraceId = '${TraceID}' )\n AND $__timeFilter(Timestamp) "
   },
   { "name": "ApplicationName", "label": "ApplicationName", "query": "All" },
   { "name": "Granularity", "label": "Granularity", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "# Agents",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(SpanAttributes['agent.name']) FROM otel_traces WHERE $__timeFilter(Timestamp)"
    }
   ]
  },
  {
   "title": "# Defined Tests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(SpanAttributes['test.name']) FROM otel_traces WHERE $__timeFilter(Timestamp)"
    }
   ]
  },
  {
   "title": "# Tests Run by Test Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SpanAttributes['test.name'] AS test_name,\n  count() AS NumTestsRun\nFROM otel_traces\nWHERE $__timeFilter(Timestamp)\n  AND notEmpty(SpanAttributes['test.name'])\nGROUP BY test_name\nORDER BY NumTestsRun DESC\n\n\n"
    }
   ]
  },
  {
   "title": "Test Trace",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \n\"Timestamp\" as startTime, \nServiceName as serviceName,\nSpanAttributes['agent.name'] as agentName,\n\"TraceId\" as traceID, \n\"SpanName\" as TestRun,\n* FROM \"default\".\"otel_traces\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) AND (('All' LIKE '${PathID}') OR (SpanAttributes['path.id'] LIKE '${PathID}')) AND ( TraceId = '${TraceID}' ) AND ( SpanAttributes['test.name'] = '${TestName}' ) AND ( SpanAttributes['agent.name'] = '${AgentName}' ) ORDER BY Timestamp DESC, Duration DESC "
    }
   ]
  },
  {
   "title": "Path Visualization",
   "type": "nodeGraph",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH hops AS (\n    SELECT\n        TraceId,\n        ServiceName,\n        SpanName,\n        arrayJoin(Events.Attributes) AS hop,\n        hop['hop'] AS hop_number,\n        hop['ip_address'] AS ip_address,\n        hop['location'] AS location,\n        hop['network'] AS network,\n        hop['prefix'] AS prefix,\n        hop['rdns'] AS rdns,\n        toInt32OrZero(hop['response_time_ms']) AS response_time_ms\n\n    FROM \"default\".\"otel_traces\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) AND (('All' LIKE '${PathID}') OR (SpanAttributes['path.id'] LIKE '${PathID}')) AND ( TraceId = '${TraceID}' )  AND ( SpanAttributes['test.name'] = '${TestName}' ) AND ( SpanAttributes['agent.name'] = '${AgentName}' ) ORDER BY Timestamp DESC\n)\n\nSELECT\n    ip_address AS id,\n    concat(\n        if(network != '', concat(' (', network, ')'), ''),\n        ' ',\n        ip_address\n    ) AS title,\n    10 AS nodeRadius\nFROM hops\nGROUP BY ServiceName, ip_address, network\n\n"
    },
    {
     "rawSql": "\n  WITH trace_hops AS (\n      SELECT\n          TraceId,\n          ServiceName,\n          SpanName,\n          -- Events.Name and Events.Attributes are parallel arrays\n          arrayFilter((name, attr) -> name = 'hop_details',\n                     Events.Name, Events.Attributes) AS hop_events_filtered,\n          arrayFilter(attr ->\n                     arrayElement(Events.Name, indexOf(Events.Attributes, attr)) = 'hop_details',\n                     Events.Attributes) AS hop_attributes\n      FROM otel_traces\n      WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) AND (('All' LIKE '${PathID}') OR (SpanAttributes['path.id'] LIKE '${PathID}')) AND ( TraceId = '${TraceID}' )  AND ( SpanAttributes['test.name'] = '${TestName}' ) AND ( SpanAttributes['agent.name'] = '${AgentName}' )\n  ),\n  flattened_hops AS (\n      SELECT\n          TraceId,\n          ServiceName,\n          SpanName,\n          hop_attr AS hop_attr,\n          toInt32OrZero(hop_attr['hop']) AS hop_number,\n          hop_attr['ip_address'] AS ip_address,\n          hop_attr['location'] AS location,\n          hop_attr['network'] AS network,\n          toInt32OrZero(hop_attr['response_time_ms']) AS response_time_ms\n      FROM trace_hops\n      ARRAY JOIN hop_attributes AS hop_attr\n  ),\n  hop_pairs AS (\n      SELECT\n          h1.TraceId,\n          h1.hop_number AS hop_from_num,\n          h2.hop_number AS hop_to_num,\n          h1.ip_address AS source,\n          h2.ip_address AS target,\n          h1.response_time_ms AS source_latency,\n          h2.response_time_ms AS target_latency,\n          h1.location AS source_location,\n          h2.location AS target_location\n      FROM flattened_hops h1\n      INNER JOIN flattened_hops h2\n          ON h1.TraceId = h2.TraceId\n          AND h2.hop_number = h1.hop_number + 1\n  )\n  SELECT\n      source,\n      target,\n      concat(\n          source,\n          ' -> ',\n          target,\n          ' (',\n          toString(target_latency),\n          'ms)'\n      ) AS id,\n      target_latency AS mainstat\n  FROM hop_pairs\n  ORDER BY hop_from_num"
    }
   ]
  },
  {
   "title": "Path Availability",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfMinute(Timestamp) AS time, \n    if(sum(length(Events.Attributes)) > 0, 100, 0) AS Value\nFROM \"default\".\"otel_traces\"\nWHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) AND ( SpanAttributes['test.name'] = '${TestName}' ) AND ( SpanAttributes['agent.name'] = '${AgentName}' ) \nGROUP BY time\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Path Latency",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "  SELECT\n    Timestamp,\n    AVG(toInt32OrZero(hop['response_time_ms'])) AS response_time_ms\nFROM otel_traces\nARRAY JOIN Events.Attributes AS hop\nWHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime )  AND ( SpanAttributes['test.name'] = '${TestName}' ) AND ( SpanAttributes['agent.name'] = '${AgentName}' ) \nGROUP BY Timestamp,SpanAttributes['test_name']\nORDER BY Timestamp ASC\n"
    }
   ]
  },
  {
   "title": "${ApplicationName} Traffic on Path by Application/Dscp (Bits/sec)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    time AS Time,\n    8*(SUM(SumOctets)/5/60) AS value,\n    concat(ApplicationName, ':', toString(d.name)) AS metric\nFROM livenx_flowdb.basic_entity_app_5m_dist\nJOIN livenx_flowdb.dscp AS d ON toUInt8(Dscp) = d.dscp\nWHERE time >= 1708095952 AND time <= 1708096852 AND (ApplicationName, Dscp) GLOBAL IN \n(\n    SELECT\n        ApplicationName, Dscp\n    FROM livenx_flowdb.basic_entity_app_5m_dist\n    JOIN livenx_flowdb.dscp AS d ON toUInt8(Dscp) = d.dscp\n    WHERE time >= 1708095952 AND time <= 1708096852 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\n    GROUP BY ApplicationName, Dscp\n    ORDER BY SUM(SumOctets) DESC\n    LIMIT 10\n)\n\nGROUP BY Time,metric\nORDER BY Time",
     "rawSql": "SELECT\n    time AS Time,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    concat(ApplicationName, ':', toString(Dscp)) AS metric\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) AND (ApplicationName, Dscp) GLOBAL IN \n(\n    SELECT\n        ApplicationName, toString(Dscp)\n    FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n    WHERE $__timeFilter(time) AND \n    (('All' LIKE '${ApplicationName}') OR (ApplicationName LIKE '${ApplicationName}'))\n    GROUP BY ApplicationName, toString(Dscp)\n    ORDER BY SUM(SumOctets) DESC\n    LIMIT 10\n)\n\nGROUP BY Time,metric\nORDER BY Time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "LiveWire Alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp, count() FROM otel_logs WHERE $__timeFilter(Timestamp)  GROUP BY Timestamp"
    }
   ]
  },
  {
   "title": "LiveWire Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT  Timestamp, LogAttributes['event_description'] AS Event,LogAttributes FROM otel_logs WHERE $__timeFilter(Timestamp)  LIMIT 100"
    }
   ]
  }
 ]
}