#!/usr/bin/env bash
# =============================================================================
# DISA STIG Ubuntu 22.04 LTS — Stage 3 Remediation: HIGH RISK
# LiveNX Platform
#
# Rules covered : 9 of 99 failing
# Risk          : HIGH — GRUB kernel params, UMASK, system binary/library perms
# Prerequisites : Stage 1 and Stage 2 must have been run and verified first
# Reboot needed : YES — GRUB changes require reboot (V-260471, V-260472)
#
# ⚠ TAKE A SNAPSHOT OF THE VM BEFORE RUNNING THIS SCRIPT ⚠
#
# Why these are HIGH RISK:
#   V-260471/472 : Bad GRUB config can prevent the server from booting
#   V-260486/487 : Changing permissions on system binaries/libraries can break
#                  LiveNX if it owns any of those files
#   V-260488     : Changing ownership of world-writable dirs could break shared
#                  app directories used by LiveNX processes
#   V-260495/496 : chown/chgrp root on system commands — same risk as above
#   V-260555     : UMASK=077 means all new files are not group-readable; LiveNX
#                  processes that create files for inter-service use may break
#   V-260556     : Removing world-write from all files — broad scan, could touch
#                  LiveNX socket files, temp files, or IPC files
#
# tmpfiles.d strategy (per dev team guidance):
#   Permissions outside /etc, /home, /var will not persist across reboots because
#   LiveNX may recreate those paths from its own packaging. This script:
#     1. Applies the fix immediately (takes effect now)
#     2. Writes /etc/tmpfiles.d/stig-file-perms.conf entries (reapplied each boot)
#   NOTE: A LiveNX version upgrade may reset these permissions. After any LiveNX
#         upgrade, verify with stig_audit.py and re-run this script if needed.
#         Long-term fix: have engineering bake these into the LiveNX release image.
#
# Run as root:
#   sudo bash /home/admin/stig_stage3_high_risk.sh 2>&1 | tee /home/admin/stig_stage3.log
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

PASS=0; FAIL=0; SKIP=0

ok()      { echo -e "  ${GREEN}✓${NC} $*"; (( PASS++ )) || true; }
fail()    { echo -e "  ${RED}✗${NC} $*"; (( FAIL++ )) || true; }
info()    { echo -e "  ${CYAN}→${NC} $*"; }
warn()    { echo -e "  ${YELLOW}!${NC} $*"; (( SKIP++ )) || true; }
section() { echo -e "\n${BOLD}═══ $* ═══${NC}"; }

[[ $EUID -ne 0 ]] && { echo "ERROR: This script must be run as root."; exit 1; }

backup() {
    local f="$1"
    if [[ -f "$f" && ! -f "${f}.stig_bak" ]]; then
        cp "$f" "${f}.stig_bak"
        info "Backed up $f → ${f}.stig_bak"
    else
        info "Backup already exists or file missing: ${f}.stig_bak"
    fi
    return 0   # never let set -e abort on the [[ ]] test result
}

# Helper: apply chmod and write tmpfiles.d entry for persistence outside /etc,/home,/var
# Usage: persist_perm <path> <mode> <owner> <group>
TMPFILES_PERMS="/etc/tmpfiles.d/stig-file-perms.conf"

persist_perm() {
    local path="$1" mode="$2" owner="$3" group="$4"
    printf 'z %s %s %s %s -\n' "$path" "$mode" "$owner" "$group" >> "$TMPFILES_PERMS"
}

echo -e "\n${BOLD}STIG Stage 3 — HIGH RISK (9 rules)${NC}"
echo    "Target : LiveNX Platform (Ubuntu 22.04 LTS)"
echo    "Date   : $(date '+%Y-%m-%d %H:%M:%S')"
echo    "Log    : /home/admin/stig_stage3.log"
echo    ""
echo -e "  ${RED}⚠  THIS SCRIPT MAKES HIGH-IMPACT CHANGES  ⚠${NC}"
echo    "  Confirm you have taken a VM snapshot before continuing."
echo    ""
read -r -p "  Type 'yes' to confirm snapshot taken and proceed: " CONFIRM
if [[ "$CONFIRM" != "yes" ]]; then
    echo "  Aborted. Take a snapshot, then re-run."
    exit 0
fi

# Initialize the tmpfiles.d file
cat > "$TMPFILES_PERMS" <<'HEADER'
# STIG Stage 3 — persistent file permissions for LiveNX
# Generated by stig_stage3_high_risk.sh
# These entries are re-applied by systemd on every boot (systemd-tmpfiles --create)
# so that permission changes outside /etc, /home, /var survive reboots and
# LiveNX appliance reimaging does not reset them.
# Format: z <path> <mode> <owner> <group> <age>
#   z = adjust permissions/ownership of an existing path (does not create it)
HEADER

# =============================================================================
# GROUP 1 — GRUB kernel parameters
# =============================================================================
section "GROUP 1: GRUB kernel parameters"

GRUB_FILE="/etc/default/grub"
if [[ ! -f "$GRUB_FILE" ]]; then
    warn "V-260471/472: $GRUB_FILE not found — skipping GRUB kernel-parameter changes"
    info "  This LiveNX image does not use /etc/default/grub. Verify the bootloader:"
    info "    cat /proc/cmdline                       # current kernel boot parameters"
    info "    ls -l /etc/default/grub.d/ 2>/dev/null"
    info "    ls -l /boot/grub/ /boot/grub2/ 2>/dev/null"
    info "  Then add 'audit=1 audit_backlog_limit=8192' via the correct mechanism and reboot."
else
backup "$GRUB_FILE"

# V-260471 — audit=1 must be in kernel command line
# V-260472 — audit_backlog_limit=8192 must be in kernel command line

# Parse GRUB_CMDLINE_LINUX — handle double quotes, single quotes, and no quotes
CURRENT_LINE=$(grep '^GRUB_CMDLINE_LINUX=' "$GRUB_FILE" | head -1)
# Strip the key and any surrounding quotes (double or single)
CURRENT_PARAMS=$(echo "$CURRENT_LINE" \
    | sed 's/^GRUB_CMDLINE_LINUX=//' \
    | sed "s/^['\"]//;s/['\"]$//")
# Sanity check: if parsing failed (params still contain GRUB_CMDLINE), abort
if echo "$CURRENT_PARAMS" | grep -q 'GRUB_CMDLINE_LINUX'; then
    fail "V-260471/472: Could not parse GRUB_CMDLINE_LINUX from $GRUB_FILE"
    fail "  Manual fix: edit $GRUB_FILE and add 'audit=1 audit_backlog_limit=8192' to GRUB_CMDLINE_LINUX"
    info "  Skipping GRUB changes to avoid corrupting config"
else
NEW_PARAMS="$CURRENT_PARAMS"

if echo "$NEW_PARAMS" | grep -q 'audit=1'; then
    ok "V-260471: audit=1 already present in GRUB params"
else
    NEW_PARAMS="$NEW_PARAMS audit=1"
    ok "V-260471: Added audit=1 to GRUB kernel params"
fi

if echo "$NEW_PARAMS" | grep -q 'audit_backlog_limit='; then
    ok "V-260472: audit_backlog_limit already present in GRUB params"
else
    NEW_PARAMS="$NEW_PARAMS audit_backlog_limit=8192"
    ok "V-260472: Added audit_backlog_limit=8192 to GRUB kernel params"
fi

NEW_PARAMS=$(echo "$NEW_PARAMS" | xargs)
sed -i "s|^GRUB_CMDLINE_LINUX=.*|GRUB_CMDLINE_LINUX=\"${NEW_PARAMS}\"|" "$GRUB_FILE"

info "Running update-grub"
if command -v update-grub &>/dev/null; then
    if update-grub &>/dev/null; then
        ok "GRUB updated — changes take effect after next reboot"
    else
        fail "update-grub failed — check $GRUB_FILE manually"
    fi
elif command -v grub-mkconfig &>/dev/null; then
    if grub-mkconfig -o /boot/grub/grub.cfg &>/dev/null; then
        ok "GRUB updated via grub-mkconfig — changes take effect after next reboot"
    else
        fail "grub-mkconfig failed — check $GRUB_FILE manually"
    fi
else
    fail "Neither update-grub nor grub-mkconfig found — update GRUB manually"
fi
info "  GRUB backup: $GRUB_FILE.stig_bak"
info "  To rollback: cp $GRUB_FILE.stig_bak $GRUB_FILE && update-grub"

fi  # end sanity check block
fi  # end GRUB file existence check

# =============================================================================
# GROUP 2 — System command file permissions (V-260486, V-260495, V-260496)
# =============================================================================
section "GROUP 2: System command permissions (V-260486, V-260495, V-260496)"

# Use arrays — avoids word splitting issues and is explicit about each path
SYSCMD_DIRS=(/bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin)

# V-260486 — system commands must not be group/world-writable
info "V-260486: Scanning for group/world-writable system commands"
CMD_486=0
set +e
while IFS= read -r -d '' f; do
    CURR_MODE=$(stat -c "%a" "$f" 2>/dev/null || continue)
    NEW_MODE=$(printf "%04o" "$((8#$CURR_MODE & ~8#022))")
    chmod "$NEW_MODE" "$f" 2>/dev/null && {
        info "  V-260486 fixed: $f (was $CURR_MODE → $NEW_MODE)"
        (( CMD_486++ )) || true
        persist_perm "$f" "$NEW_MODE" root root
    }
done < <(find "${SYSCMD_DIRS[@]}" -type f -perm /022 -print0 2>/dev/null)
set -e
[[ $CMD_486 -gt 0 ]] && ok "V-260486: $CMD_486 system commands had group/world-write removed" \
                      || ok "V-260486: No group/world-writable system commands found"

# V-260495 — system commands must be owned by root
info "V-260495: Scanning for system commands not owned by root"
CMD_495=0
set +e
while IFS= read -r -d '' f; do
    CURR_MODE=$(stat -c "%a" "$f" 2>/dev/null || continue)
    chown root "$f" 2>/dev/null && {
        info "  V-260495 fixed: $f (chowned to root)"
        (( CMD_495++ )) || true
        persist_perm "$f" "$CURR_MODE" root root
    }
done < <(find "${SYSCMD_DIRS[@]}" -type f ! -user root -print0 2>/dev/null)
set -e
[[ $CMD_495 -gt 0 ]] && ok "V-260495: $CMD_495 system commands chowned to root" \
                      || ok "V-260495: All system commands already owned by root"

# V-260496 — system commands must be group-owned by root
info "V-260496: Scanning for system commands not group-owned by root"
CMD_496=0
set +e
while IFS= read -r -d '' f; do
    CURR_MODE=$(stat -c "%a" "$f" 2>/dev/null || continue)
    chgrp root "$f" 2>/dev/null && {
        info "  V-260496 fixed: $f (chgrp to root)"
        (( CMD_496++ )) || true
        persist_perm "$f" "$CURR_MODE" root root
    }
done < <(find "${SYSCMD_DIRS[@]}" -type f ! -group root -print0 2>/dev/null)
set -e
[[ $CMD_496 -gt 0 ]] && ok "V-260496: $CMD_496 system commands chgrp to root" \
                      || ok "V-260496: All system commands already group-owned by root"

# =============================================================================
# GROUP 3 — Library file permissions (V-260487)
# =============================================================================
section "GROUP 3: Library file permissions (V-260487)"

LIB_DIRS=(/lib /lib64 /usr/lib /usr/lib64)

info "V-260487: Scanning for group/world-writable library files"
LIB_487=0
set +e
while IFS= read -r -d '' f; do
    CURR_MODE=$(stat -c "%a" "$f" 2>/dev/null || continue)
    NEW_MODE=$(printf "%04o" "$((8#$CURR_MODE & ~8#022))")
    chmod "$NEW_MODE" "$f" 2>/dev/null && {
        info "  V-260487 fixed: $f (was $CURR_MODE → $NEW_MODE)"
        (( LIB_487++ )) || true
        persist_perm "$f" "$NEW_MODE" root root
    }
done < <(find "${LIB_DIRS[@]}" -type f -perm /022 -print0 2>/dev/null)
set -e
[[ $LIB_487 -gt 0 ]] && ok "V-260487: $LIB_487 library files had group/world-write removed" \
                      || ok "V-260487: No group/world-writable library files found"

# =============================================================================
# GROUP 4 — World-writable directory ownership (V-260488)
# =============================================================================
section "GROUP 4: World-writable directory ownership (V-260488)"

info "V-260488: Scanning for world-writable directories not owned by root"
DIR_488=0
set +e
while IFS= read -r -d '' d; do
    CURR_MODE=$(stat -c "%a" "$d" 2>/dev/null || continue)
    chown root "$d" 2>/dev/null && {
        info "  V-260488 fixed: $d (chowned to root)"
        ((DIR_488++)) || true
        # Only write tmpfiles.d for paths outside /etc, /home, /var
        if [[ "$d" != /etc/* && "$d" != /home/* && "$d" != /var/* ]]; then
            persist_perm "$d" "$CURR_MODE" root root
        fi
    }
done < <(find / -xdev -type d -perm -0002 ! -uid 0 -print0 2>/dev/null)
set -e
[[ $DIR_488 -gt 0 ]] && ok "V-260488: $DIR_488 world-writable directories chowned to root" \
                      || ok "V-260488: All world-writable directories already owned by root"

# =============================================================================
# GROUP 5 — UMASK (V-260555)
# =============================================================================
section "GROUP 5: Default UMASK (V-260555)"

backup /etc/login.defs

# V-260555 — UMASK must be 077 or more restrictive
info "V-260555: Setting UMASK=077 in /etc/login.defs"
info "  WARNING: UMASK=077 means new files are not readable by group or others."
info "  If LiveNX creates inter-service files expecting group-read, those may break."
info "  Monitor LiveNX logs after reboot if issues arise."
if grep -q '^UMASK' /etc/login.defs; then
    sed -i 's/^UMASK.*/UMASK\t\t077/' /etc/login.defs
else
    echo -e "UMASK\t\t077" >> /etc/login.defs
fi
ok "V-260555: UMASK=077 set in /etc/login.defs (takes effect on next login)"

# =============================================================================
# GROUP 6 — World-writable files (V-260556)
# =============================================================================
section "GROUP 6: World-writable files (V-260556)"

info "V-260556: Scanning filesystem for world-writable files (this may take a moment)"
info "  Excluding /proc, /sys, /dev to avoid kernel virtual filesystems"
FILE_556=0
set +e
while IFS= read -r -d '' f; do
    CURR_MODE=$(stat -c "%a" "$f" 2>/dev/null || continue)
    NEW_MODE=$(printf "%04o" "$((8#$CURR_MODE & ~8#002))")
    chmod o-w "$f" 2>/dev/null && {
        info "  V-260556 fixed: $f (was $CURR_MODE → $NEW_MODE)"
        ((FILE_556++)) || true
        # For files outside /etc, /home, /var persist via tmpfiles.d
        if [[ "$f" != /etc/* && "$f" != /home/* && "$f" != /var/* ]]; then
            OWNER=$(stat -c "%U" "$f" 2>/dev/null || echo "root")
            GROUP=$(stat -c "%G" "$f" 2>/dev/null || echo "root")
            persist_perm "$f" "$NEW_MODE" "$OWNER" "$GROUP"
        fi
    }
done < <(find / -xdev -type f -perm -0002 \
    ! -path "/proc/*" ! -path "/sys/*" ! -path "/dev/*" -print0 2>/dev/null)
set -e
[[ $FILE_556 -gt 0 ]] && ok "V-260556: $FILE_556 world-writable files fixed" \
                       || ok "V-260556: No world-writable files found"

# =============================================================================
# GROUP 7 — Apply tmpfiles.d and validate
# =============================================================================
section "GROUP 7: Apply and validate tmpfiles.d"

# Deduplicate z entries before applying. The same path can be touched by more
# than one rule (e.g. V-260495 chown + V-260496 chgrp both target the mongo*/
# bson* tools), which produces conflicting/duplicate lines and makes
# systemd-tmpfiles error out and skip the whole file. Keep the first entry per
# path; comment/header lines (not starting with "z ") are preserved.
if [[ -f "$TMPFILES_PERMS" ]]; then
    awk '/^z / { if (seen[$2]++) next } { print }' "$TMPFILES_PERMS" \
        > "${TMPFILES_PERMS}.dedup" && mv "${TMPFILES_PERMS}.dedup" "$TMPFILES_PERMS"
fi

ENTRY_COUNT=$(grep -c '^z ' "$TMPFILES_PERMS" 2>/dev/null || echo 0)
ok "tmpfiles.d written: $TMPFILES_PERMS ($ENTRY_COUNT unique entries)"
info "  Applying tmpfiles.d now to confirm entries are valid"
# Capture stderr so any remaining issues are visible in the log, not hidden.
if TMPFILES_ERR=$(systemd-tmpfiles --create "$TMPFILES_PERMS" 2>&1); then
    ok "tmpfiles.d applied successfully (will re-apply automatically on each boot)"
else
    warn "systemd-tmpfiles reported issues:"
    echo "$TMPFILES_ERR" | sed 's/^/        /'
    info "  Manual apply: systemd-tmpfiles --create $TMPFILES_PERMS"
fi

info "NOTE: A LiveNX version upgrade may reset binary permissions."
info "      After any LiveNX upgrade, re-run this script or verify with stig_audit.py."
info "      Permanent fix: ask engineering to bake permissions into the LiveNX release image."

# =============================================================================
# SUMMARY
# =============================================================================
section "STAGE 3 SUMMARY"

echo ""
echo -e "  ${GREEN}Applied successfully : ${PASS}${NC}"
echo -e "  ${RED}Failed               : ${FAIL}${NC}"
echo -e "  ${YELLOW}Warned/skipped       : ${SKIP}${NC}"
echo ""
echo "  Rules covered:"
echo "    V-260471 V-260472 (GRUB — reboot required)"
echo "    V-260486 V-260487 V-260488 V-260495 V-260496 (file/dir permissions)"
echo "    V-260555 (UMASK)"
echo "    V-260556 (world-writable files)"
echo ""
echo -e "  ${YELLOW}REBOOT REQUIRED${NC} for GRUB changes to take effect:"
echo    "    sudo reboot"
echo ""
echo "  After reboot, run the audit to see progress:"
echo "    python3 /home/admin/stig_audit.py --output-dir /home/admin/reports"
echo ""
echo "  MONITOR after reboot:"
echo "    - LiveNX web UI accessible"
echo "    - LiveNX services running: systemctl status livenx* (or relevant service name)"
echo "    - No unusual errors in: journalctl -xe"
echo ""
echo "  tmpfiles.d config: $TMPFILES_PERMS"
echo "  If a permission change broke something, remove the relevant line from that file"
echo "  and restore with: cp <file>.stig_bak <file>"
echo ""
