#
# Splunk app configuration file
#

[install]
is_configured = 0
build = 7

[ui]
is_visible = 1
label = BlueCat Network Observability App for Splunk

[launcher]
author = BlueCat Networks
description = Contains dashboards for ipfix/oTel traffic being sent from LiveWires and OTel from LiveNX.
version = 26.3.0

[package]
id = livewire_app