[livewire_netflow]
definition = source="stream:livewire_livewire_netflow" netflowdata

[livewire_app]
definition = eval Name=replace(app_tag, " : .*", ""), sel_id=tonumber(replace(app_tag, ".* : ", ""), 16) | lookup classification_engine_mappings Name OUTPUT ID AS cl_eng_id | lookup livewire_mappings cl_eng_id sel_id OUTPUT Application

[livewire_otlp]
definition = sourcetype="splunk-connect-for-otlp" receiver_type="livewire" | eval saddr=if(addrs_are_ipv4="true", replace(saddr, "^::ffff:", ""), saddr), daddr=if(addrs_are_ipv4="true", replace(daddr, "^::ffff:", ""), daddr)
