{
 "title": "Device Information",
 "tags": [
  "inventory",
  "datamodel",
  "opentelemetry"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Granularity",
    "label": "Granularity",
    "query": "1m : 1,5m : 5,60m : 60,360m : 360"
   },
   {
    "name": "DeviceSerial",
    "label": "DeviceSerial",
    "query": "SELECT DISTINCT Serial FROM inventory_db.Device_Inventory"
   },
   {
    "name": "Application",
    "label": "ApplicationName",
    "query": "SELECT DISTINCT ApplicationName FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE\n       $__timeFilter(time)"
   },
   {
    "name": "Dscp",
    "label": "Dscp",
    "query": "SELECT DISTINCT Dscp AS Dscp FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist as f\nWHERE\n       $__timeFilter(time)"
   }
  ]
 },
 "panels": [
  {
   "title": "Device Interface Volume (bits/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "WITH RawData AS (\n    SELECT \n        TimeUnix,\n        DeviceID,\n        SUM(Value) AS InterfaceBytesTotal\n    FROM (\n        SELECT \n            TimeUnix,\n            ResourceAttributes['device.id'] AS DeviceID,\n            Value\n        FROM \"default\".\"otel_metrics_sum\"\n        WHERE MetricName = 'ifInOctets'\n        AND (TimeUnix >= $__fromTime AND TimeUnix <= $__toTime)\n        AND (('All' LIKE '${DeviceSerial}') OR (ResourceAttributes['device.id'] LIKE '${DeviceSerial}'))\n    )\n    GROUP BY TimeUnix, DeviceID\n)\nSELECT \n    TimeUnix,\n    DeviceID,\n    if(prev_bytes IS NULL OR time_diff = 0, 0,\n        (InterfaceBytesTotal - prev_bytes) / time_diff\n    ) AS InterfaceBytesRate\nFROM (\n    SELECT \n        TimeUnix,\n        DeviceID,\n        InterfaceBytesTotal,\n        lagInFrame(InterfaceBytesTotal) OVER (PARTITION BY DeviceID ORDER BY TimeUnix) AS prev_bytes,\n        toUnixTimestamp64Nano(TimeUnix) - toUnixTimestamp64Nano(lagInFrame(TimeUnix) OVER (PARTITION BY DeviceID ORDER BY TimeUnix)) AS time_diff\n    FROM RawData\n)\nORDER BY TimeUnix ASC;"
    },
    {
     "rawSql": "WITH RawData AS (\n    SELECT \n        TimeUnix,\n        DeviceID,\n        SUM(Value) AS InterfaceBytesTotal\n    FROM (\n        SELECT \n            TimeUnix,\n            ResourceAttributes['device.id'] AS DeviceID,\n            Value\n        FROM \"default\".\"otel_metrics_sum\"\n        WHERE MetricName = 'ifOutOctets'\n        AND (TimeUnix >= $__fromTime AND TimeUnix <= $__toTime)\n        AND (('All' LIKE '${DeviceSerial}') OR (ResourceAttributes['device.id'] LIKE '${DeviceSerial}'))\n    )\n    GROUP BY TimeUnix, DeviceID\n)\nSELECT \n    TimeUnix,\n    DeviceID,\n    if(prev_bytes IS NULL OR time_diff = 0, 0,\n        (InterfaceBytesTotal - prev_bytes) / time_diff\n    ) AS InterfaceBytesRate\nFROM (\n    SELECT \n        TimeUnix,\n        DeviceID,\n        InterfaceBytesTotal,\n        lagInFrame(InterfaceBytesTotal) OVER (PARTITION BY DeviceID ORDER BY TimeUnix) AS prev_bytes,\n        toUnixTimestamp64Nano(TimeUnix) - toUnixTimestamp64Nano(lagInFrame(TimeUnix) OVER (PARTITION BY DeviceID ORDER BY TimeUnix)) AS time_diff\n    FROM RawData\n)\nORDER BY TimeUnix ASC;"
    }
   ]
  },
  {
   "title": "Device Interface Inbound Volume (ifInOctets) (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "WITH RawData AS (\n    SELECT \n        TimeUnix,\n        DeviceID,\n        SUM(Value) AS InterfaceBytesTotal\n    FROM (\n        SELECT \n            TimeUnix,\n            ResourceAttributes['device.id'] AS DeviceID,\n            Value\n        FROM \"default\".\"otel_metrics_sum\"\n        WHERE MetricName = 'ifInOctets'\n        AND (TimeUnix >= $__fromTime AND TimeUnix <= $__toTime)\n        AND (('All' LIKE '${DeviceSerial}') OR (ResourceAttributes['device.id'] LIKE '${DeviceSerial}'))\n    )\n    GROUP BY TimeUnix, DeviceID\n)\nSELECT \n    TimeUnix,\n    DeviceID,\n    if(prev_bytes IS NULL OR time_diff = 0, 0,\n        (InterfaceBytesTotal - prev_bytes) / time_diff\n    ) AS InterfaceBytesRate\nFROM (\n    SELECT \n        TimeUnix,\n        DeviceID,\n        InterfaceBytesTotal,\n        lagInFrame(InterfaceBytesTotal) OVER (PARTITION BY DeviceID ORDER BY TimeUnix) AS prev_bytes,\n        toUnixTimestamp64Nano(TimeUnix) - toUnixTimestamp64Nano(lagInFrame(TimeUnix) OVER (PARTITION BY DeviceID ORDER BY TimeUnix)) AS time_diff\n    FROM RawData\n)\nORDER BY TimeUnix ASC;"
    }
   ]
  },
  {
   "title": "Device Interface Outbound Volume (ifOutOctets)  (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "WITH RawData AS (\n    SELECT \n        TimeUnix,\n        DeviceID,\n        SUM(Value) AS InterfaceBytesTotal\n    FROM (\n        SELECT \n            TimeUnix,\n            ResourceAttributes['device.id'] AS DeviceID,\n            Value\n        FROM \"default\".\"otel_metrics_sum\"\n        WHERE MetricName = 'ifInOctets'\n        AND (TimeUnix >= $__fromTime AND TimeUnix <= $__toTime)\n        AND (('All' LIKE '${DeviceSerial}') OR (ResourceAttributes['device.id'] LIKE '${DeviceSerial}'))\n    )\n    GROUP BY TimeUnix, DeviceID\n)\nSELECT \n    TimeUnix,\n    DeviceID,\n    if(prev_bytes IS NULL OR time_diff = 0, 0,\n        (InterfaceBytesTotal - prev_bytes) / time_diff\n    ) AS InterfaceBytesRate\nFROM (\n    SELECT \n        TimeUnix,\n        DeviceID,\n        InterfaceBytesTotal,\n        lagInFrame(InterfaceBytesTotal) OVER (PARTITION BY DeviceID ORDER BY TimeUnix) AS prev_bytes,\n        toUnixTimestamp64Nano(TimeUnix) - toUnixTimestamp64Nano(lagInFrame(TimeUnix) OVER (PARTITION BY DeviceID ORDER BY TimeUnix)) AS time_diff\n    FROM RawData\n)\nORDER BY TimeUnix ASC;"
    }
   ]
  },
  {
   "title": "Total Traffic by Flow Type (Bits/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    time AS Time,\n    8*(SUM(SumOctets)/5/60) AS value,\n    concat(ApplicationName, ':', toString(d.name)) AS metric\nFROM livenx_flowdb.basic_entity_app_5m_dist\nJOIN livenx_flowdb.dscp AS d ON toUInt8(Dscp) = d.dscp\nWHERE time >= 1708095952 AND time <= 1708096852 AND (ApplicationName, Dscp) GLOBAL IN \n(\n    SELECT\n        ApplicationName, Dscp\n    FROM livenx_flowdb.basic_entity_app_5m_dist\n    JOIN livenx_flowdb.dscp AS d ON toUInt8(Dscp) = d.dscp\n    WHERE time >= 1708095952 AND time <= 1708096852 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\n    GROUP BY ApplicationName, Dscp\n    ORDER BY SUM(SumOctets) DESC\n    LIMIT 10\n)\n\nGROUP BY Time,metric\nORDER BY Time",
     "rawSql": "SELECT\n    time AS Time,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    'Basic' AS metric\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) AND\n    (('All' LIKE '${Dscp}') OR (toString(Dscp) LIKE '${Dscp}')) AND \n    (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND \n    (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}'))\nGROUP BY Time,metric\nORDER BY Time",
     "round": "0s"
    },
    {
     "rawSql": "SELECT\n    time AS Time,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    'AVC' AS metric\nFROM livenx_flowdb.avc_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) AND\n    (('All' LIKE '${Dscp}') OR (toString(Dscp) LIKE '${Dscp}')) AND \n    (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND \n    (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}'))\nGROUP BY Time,metric\nORDER BY Time"
    },
    {
     "rawSql": "SELECT\n    time AS Time,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    'MediaNet' AS metric\nFROM livenx_flowdb.medianet_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) AND\n    (('All' LIKE '${Dscp}') OR (toString(Dscp) LIKE '${Dscp}')) AND \n    (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND \n    (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}'))\nGROUP BY Time,metric\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Basic Traffic by Device (Bytes)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    d.name AS Dscp,\n    SUM(SumOctets)/5 AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets)/5 AS TotalPackets,\n    SUM(SumOctets)*8/5/60 AS AverageBitRate,\n    AVG(SumPackets)/5/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/5/60 AS PeakBitRate,\n    MAX(SumPackets)/5/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_5m_dist as f\nJOIN livenx_flowdb.dscp AS d ON toUInt8(f.Dscp) = d.dscp\nWHERE\n    time >= 1708095989 AND time <= 1708096889 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND  \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName, Dscp\nLIMIT 1000",
     "rawSql": "SELECT\n    DeviceSerial,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    SUM(SumFlowCount) AS FlowCount\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) AND\n    (('All' LIKE '${Dscp}') OR (toString(Dscp) LIKE '${Dscp}')) AND \n    (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND \n    (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}'))\nGROUP BY DeviceSerial",
     "round": "0s"
    }
   ]
  },
  {
   "title": "AVC Traffic by Device (Bytes)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    d.name AS Dscp,\n    SUM(SumOctets)/5 AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets)/5 AS TotalPackets,\n    SUM(SumOctets)*8/5/60 AS AverageBitRate,\n    AVG(SumPackets)/5/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/5/60 AS PeakBitRate,\n    MAX(SumPackets)/5/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_5m_dist as f\nJOIN livenx_flowdb.dscp AS d ON toUInt8(f.Dscp) = d.dscp\nWHERE\n    time >= 1708095989 AND time <= 1708096889 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND  \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName, Dscp\nLIMIT 1000",
     "rawSql": "SELECT\n    DeviceSerial,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    SUM(SumFlowCount) AS FlowCount\nFROM livenx_flowdb.avc_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) AND\n    (('All' LIKE '${Dscp}') OR (toString(Dscp) LIKE '${Dscp}')) AND \n    (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND \n    (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}'))\nGROUP BY DeviceSerial",
     "round": "0s"
    }
   ]
  },
  {
   "title": "MediaNet Traffic by Device (Bytes)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    d.name AS Dscp,\n    SUM(SumOctets)/5 AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets)/5 AS TotalPackets,\n    SUM(SumOctets)*8/5/60 AS AverageBitRate,\n    AVG(SumPackets)/5/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/5/60 AS PeakBitRate,\n    MAX(SumPackets)/5/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_5m_dist as f\nJOIN livenx_flowdb.dscp AS d ON toUInt8(f.Dscp) = d.dscp\nWHERE\n    time >= 1708095989 AND time <= 1708096889 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND  \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName, Dscp\nLIMIT 1000",
     "rawSql": "SELECT\n    DeviceSerial,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    SUM(SumFlowCount) AS FlowCount\nFROM livenx_flowdb.medianet_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) AND\n    (('All' LIKE '${Dscp}') OR (toString(Dscp) LIKE '${Dscp}')) AND \n    (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND \n    (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}'))\nGROUP BY DeviceSerial",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Device Config Changes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    d.name AS Dscp,\n    SUM(SumOctets)/5 AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets)/5 AS TotalPackets,\n    SUM(SumOctets)*8/5/60 AS AverageBitRate,\n    AVG(SumPackets)/5/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/5/60 AS PeakBitRate,\n    MAX(SumPackets)/5/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_5m_dist as f\nJOIN livenx_flowdb.dscp AS d ON toUInt8(f.Dscp) = d.dscp\nWHERE\n    time >= 1708095989 AND time <= 1708096889 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND  \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName, Dscp\nLIMIT 1000",
     "rawSql": "SELECT\n    Fetch_Time,count()\nFROM inventory_db.Audit_Log\nWHERE \n    (('All' LIKE '${DeviceSerial}') OR (Device_Serial LIKE '${DeviceSerial}'))\nGROUP BY Fetch_Time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Device Config Audit Log",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    d.name AS Dscp,\n    SUM(SumOctets)/5 AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets)/5 AS TotalPackets,\n    SUM(SumOctets)*8/5/60 AS AverageBitRate,\n    AVG(SumPackets)/5/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/5/60 AS PeakBitRate,\n    MAX(SumPackets)/5/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_5m_dist as f\nJOIN livenx_flowdb.dscp AS d ON toUInt8(f.Dscp) = d.dscp\nWHERE\n    time >= 1708095989 AND time <= 1708096889 AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND \n    (('All' LIKE 'All') OR (d.name LIKE 'All')) AND  \n    (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName, Dscp\nLIMIT 1000",
     "rawSql": "SELECT\n    *\nFROM inventory_db.Audit_Log\nWHERE \n    (('All' LIKE '${DeviceSerial}') OR (Device_Serial LIKE '${DeviceSerial}'))",
     "round": "0s"
    }
   ]
  }
 ]
}