{
 "title": "Site",
 "tags": [
  "inventory",
  "datamodel"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Granularity",
    "label": "Granularity",
    "query": "1m : 1,5m : 5,60m : 60,360m : 360"
   },
   {
    "name": "Application",
    "query": "SELECT DISTINCT ApplicationName FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE\n       $__timeFilter(time)"
   },
   {
    "name": "DeviceSerial",
    "label": "DeviceSerial",
    "query": "SELECT DISTINCT DeviceSerial FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE\n       $__timeFilter(time)"
   },
   {
    "name": "Site_Name",
    "label": "Site",
    "query": "SELECT DISTINCT Site FROM inventory_db.Device_Inventory"
   }
  ]
 },
 "panels": [
  {
   "title": "Devices In Site",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM inventory_db.Device_Inventory  WHERE (('All' LIKE '${Site_Name}') OR (Site LIKE '${Site_Name}'))"
    }
   ]
  },
  {
   "title": "Total Traffic by Application Name (Bits/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    time AS Time,\n    8*(SUM(SumOctets)/1/60) AS value,\n    ApplicationName AS metric\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE time >= 1560296996 AND time <= 1561104323 AND (ApplicationName) GLOBAL IN \n(\n    SELECT\n        ApplicationName\n    FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n    WHERE time >= 1560296996 AND time <= 1561104323 AND ApplicationName != 'unknown' AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\n    GROUP BY ApplicationName\n    ORDER BY SUM(SumOctets) DESC\n    LIMIT 10\n)\n\nGROUP BY Time,metric\nORDER BY Time",
     "rawSql": "SELECT \n    time AS Time,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    ApplicationName AS metric\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time) AND (ApplicationName) GLOBAL IN \n(\n    SELECT\n        ApplicationName\n    FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n    WHERE $__timeFilter(time) AND ApplicationName != 'unknown' AND \n    (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')) AND (('All' LIKE '${Site_Name}') OR (DeviceSiteName LIKE '${Site_Name}'))\n    GROUP BY ApplicationName\n    ORDER BY SUM(SumOctets) DESC\n    LIMIT 10\n)\n\nGROUP BY Time,metric\nORDER BY Time",
     "round": "0s"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    time AS Time,\n    8*(SUM(SumOctets)/1/60) AS value,\n    ApplicationName AS metric\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE time >= 1560296996 AND time <= 1561104323 AND (ApplicationName) GLOBAL IN \n(\n    SELECT\n        ApplicationName\n    FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n    WHERE time >= 1560296996 AND time <= 1561104323 AND ApplicationName != 'unknown' AND \n    (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\n    GROUP BY ApplicationName\n    ORDER BY SUM(SumOctets) DESC\n    LIMIT 10\n)\n\nGROUP BY Time,metric\nORDER BY Time",
     "rawSql": "SELECT\n    time AS Time,\n    8*(SUM(SumOctets)/${Granularity}/60) AS Traffic,\n    'Total' AS metric\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE $__timeFilter(time)\nGROUP BY Time,metric\nORDER BY Time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Traffic by Application Name - Inbound/Outbound (Bytes)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    SUM(SumOctets) AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets) AS TotalPackets,\n    SUM(SumOctets)*8/1/60 AS AverageBitRate,\n    AVG(SumPackets)/1/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/1/60 AS PeakBitRate,\n    MAX(SumPackets)/1/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE\n    time >= 1705950483 AND time <= 1705954083 AND ApplicationName != 'unknown' AND (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND (('All' LIKE 'server2-flowgen1-node1') OR (DeviceSerial LIKE 'server2-flowgen1-node1'))\nGROUP BY ApplicationName\nLIMIT 1000",
     "rawSql": "\nWITH\nTop1000Applications AS (\n    SELECT\n        ApplicationName,\n        SUM(SumOctets) AS TotalBytes,\n        SUM(SumFlowCount) AS TotalFlows,\n        SUM(SumPackets) AS TotalPackets,\n        SUM(SumOctets)*8/($__toTime - $__fromTime) AS AverageBitRate,\n        SUM(SumPackets)/($__toTime - $__fromTime) AS AveragePacketRate\n    FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n    WHERE ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')) AND (('All' LIKE '${Site_Name}') OR (DeviceSiteName LIKE '${Site_Name}')))\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n)\nSELECT  \n    A.ApplicationName AS ApplicationName,\n    A.TotalBytes AS TotalBytes,\n    A.TotalFlows AS TotalFlows,\n    A.TotalPackets AS TotalPackets,\n    A.AverageBitRate AS AverageBitRate,\n    A.AveragePacketRate AS AveragePacketRate,\n    B.PeakPacketRate AS PeakPacketRate,\n    C.PeakBitRate AS PeakBitRate\nFROM Top1000Applications A\nJOIN (\n    SELECT ApplicationName,MAX(SumSumPackets)/${Granularity}/60 AS PeakPacketRate, SUM(SumSumOctets) AS TotalBytes\n    FROM\n    (\n        SELECT\n            ApplicationName,\n            time,\n            SUM(SumPackets) AS SumSumPackets,\n            SUM(SumOctets) AS SumSumOctets\n        FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n        WHERE ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')))\n        GROUP BY time, ApplicationName\n    ) AS subquery\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n) AS B ON A.ApplicationName = B.ApplicationName\nJOIN (\n    SELECT ApplicationName,(MAX(SumSumOctets)*8)/${Granularity}/60 AS PeakBitRate, SUM(SumSumOctets) AS TotalBytes\n    FROM\n    (\n        SELECT\n            ApplicationName,\n            time,\n            SUM(SumOctets) AS SumSumOctets\n        FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n        WHERE ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')))\n        GROUP BY time, ApplicationName\n    ) AS subquery\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n) AS C ON A.ApplicationName = C.ApplicationName\nORDER BY TotalBytes DESC;\n\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Traffic by Application Name - Inbound (Bytes)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    SUM(SumOctets) AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets) AS TotalPackets,\n    SUM(SumOctets)*8/1/60 AS AverageBitRate,\n    AVG(SumPackets)/1/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/1/60 AS PeakBitRate,\n    MAX(SumPackets)/1/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE\n    time >= 1706108576 AND time <= 1706151776 AND FlowDirection == 0 AND ApplicationName != 'unknown' AND (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName\nLIMIT 1000",
     "rawSql": "WITH\nTop1000Applications AS (\n    SELECT\n        ApplicationName,\n        SUM(SumOctets) AS TotalBytes,\n        SUM(SumFlowCount) AS TotalFlows,\n        SUM(SumPackets) AS TotalPackets,\n        SUM(SumOctets)*8/($__toTime - $__fromTime) AS AverageBitRate,\n        SUM(SumPackets)/($__toTime - $__fromTime) AS AveragePacketRate\n    FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n    WHERE FlowDirection == 0 AND ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')) AND (('All' LIKE '${Site_Name}') OR (DeviceSiteName LIKE '${Site_Name}')))\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n)\nSELECT  \n    A.ApplicationName AS ApplicationName,\n    A.TotalBytes AS TotalBytes,\n    A.TotalFlows AS TotalFlows,\n    A.TotalPackets AS TotalPackets,\n    A.AverageBitRate AS AverageBitRate,\n    A.AveragePacketRate AS AveragePacketRate,\n    B.PeakPacketRate AS PeakPacketRate,\n    C.PeakBitRate AS PeakBitRate\nFROM Top1000Applications A\nJOIN (\n    SELECT ApplicationName,MAX(SumSumPackets)/${Granularity}/60 AS PeakPacketRate, SUM(SumSumOctets) AS TotalBytes\n    FROM\n    (\n        SELECT\n            ApplicationName,\n            time,\n            SUM(SumPackets) AS SumSumPackets,\n            SUM(SumOctets) AS SumSumOctets\n        FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n        WHERE FlowDirection == 0 AND ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')))\n        GROUP BY time, ApplicationName\n    ) AS subquery\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n) AS B ON A.ApplicationName = B.ApplicationName\nJOIN (\n    SELECT ApplicationName,(MAX(SumSumOctets)*8)/${Granularity}/60 AS PeakBitRate, SUM(SumSumOctets) AS TotalBytes\n    FROM\n    (\n        SELECT\n            ApplicationName,\n            time,\n            SUM(SumOctets) AS SumSumOctets\n        FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n        WHERE FlowDirection == 0 AND ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')))\n        GROUP BY time, ApplicationName\n    ) AS subquery\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n) AS C ON A.ApplicationName = C.ApplicationName\nORDER BY TotalBytes DESC;\n\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Traffic by Application Name - Outbound (Bytes)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "timeslot",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $__timeFilter(time) GROUP BY t ORDER BY t",
     "rawQuery": "SELECT \n    ApplicationName,\n    SUM(SumOctets) AS TotalBytes,\n    SUM(SumFlowCount) AS TotalFlows,\n    SUM(SumPackets) AS TotalPackets,\n    SUM(SumOctets)*8/1/60 AS AverageBitRate,\n    AVG(SumPackets)/1/60 AS AveragePacketRate,\n    MAX(SumOctets)*8/1/60 AS PeakBitRate,\n    MAX(SumPackets)/1/60 AS PeakPacketRate\nFROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\nWHERE\n    time >= 1706108617 AND time <= 1706151817 AND FlowDirection == 1 AND ApplicationName != 'unknown' AND (('All' LIKE 'All') OR (ApplicationName LIKE 'All')) AND (('All' LIKE 'All') OR (DeviceSerial LIKE 'All'))\nGROUP BY ApplicationName\nLIMIT 1000",
     "rawSql": "WITH\nTop1000Applications AS (\n    SELECT\n        ApplicationName,\n        SUM(SumOctets) AS TotalBytes,\n        SUM(SumFlowCount) AS TotalFlows,\n        SUM(SumPackets) AS TotalPackets,\n        SUM(SumOctets)*8/($__toTime - $__fromTime) AS AverageBitRate,\n        SUM(SumPackets)/($__toTime - $__fromTime) AS AveragePacketRate\n    FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n    WHERE FlowDirection == 1 AND ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')) AND (('All' LIKE '${Site_Name}') OR (DeviceSiteName LIKE '${Site_Name}')))\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n)\nSELECT  \n    A.ApplicationName AS ApplicationName,\n    A.TotalBytes AS TotalBytes,\n    A.TotalFlows AS TotalFlows,\n    A.TotalPackets AS TotalPackets,\n    A.AverageBitRate AS AverageBitRate,\n    A.AveragePacketRate AS AveragePacketRate,\n    B.PeakPacketRate AS PeakPacketRate,\n    C.PeakBitRate AS PeakBitRate\nFROM Top1000Applications A\nJOIN (\n    SELECT ApplicationName,MAX(SumSumPackets)/${Granularity}/60 AS PeakPacketRate, SUM(SumSumOctets) AS TotalBytes\n    FROM\n    (\n        SELECT\n            ApplicationName,\n            time,\n            SUM(SumPackets) AS SumSumPackets,\n            SUM(SumOctets) AS SumSumOctets\n        FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n        WHERE FlowDirection == 1 AND ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')))\n        GROUP BY time, ApplicationName\n    ) AS subquery\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n) AS B ON A.ApplicationName = B.ApplicationName\nJOIN (\n    SELECT ApplicationName,(MAX(SumSumOctets)*8)/${Granularity}/60 AS PeakBitRate, SUM(SumSumOctets) AS TotalBytes\n    FROM\n    (\n        SELECT\n            ApplicationName,\n            time,\n            SUM(SumOctets) AS SumSumOctets\n        FROM livenx_flowdb.basic_entity_app_${Granularity}m_dist\n        WHERE FlowDirection == 1 AND ($__timeFilter(time) AND ApplicationName != 'unknown' AND (('All' LIKE '${Application}') OR (ApplicationName LIKE '${Application}')) AND (('All' LIKE '${DeviceSerial}') OR (DeviceSerial LIKE '${DeviceSerial}')))\n        GROUP BY time, ApplicationName\n    ) AS subquery\n    GROUP BY ApplicationName\n    ORDER BY TotalBytes DESC\n    LIMIT 1000\n) AS C ON A.ApplicationName = C.ApplicationName\nORDER BY TotalBytes DESC;\n\n",
     "round": "0s"
    }
   ]
  }
 ]
}